### ISSUE TITLE
explicitly state that the hackathon is 36 hours

### ISSUE THREAD

**Issue by egladman** [BuckeyeHackers/ohio#36]
No where on the site does it say how long the event is.

**Comment by mattfxyz** [comment]
Hackathon is 24 hours.

**Comment by KevinPayravi** [comment]
I think it's about time to shift the "about" section to more about this year's hackathon, and less about last year's?

**Comment by arnabdotorg** [comment]
Pl. See Media Snippets document in Drive ("longer version for students" and copy paste for now, we can customize later.

**Comment by mattfxyz** [comment]
Updated. Just need to push it live.
