### ISSUE TITLE
Add Timeline

### ISSUE THREAD

**Issue by arnabdotorg** [BuckeyeHackers/ohio#37]
- [ ] See http://codepen.io/agrimsrud/pen/vtoqy 
- [ ] Basic events to add: [ Registration, Hacking Starts, Food Events, Judging, Showcase, Prizes, Networking ] -- see Master Schedule in Drive for exact times

**Comment by mattfxyz** [comment]
This will also work. Looks more interactive? https://github.com/rpocklin/angular-timeline

**Comment by mattfxyz** [comment]
Used angular timeline. It integrates with google sheets :+1:
