### ISSUE TITLE
Add Venue

### ISSUE THREAD

**Issue by arnabdotorg** [BuckeyeHackers/ohio#38]
- [x] Change "November 14th-15th" to "November 14<sup>th</sup>-15<sup>th</sup> at the Ohio Union"
- [x] Add Picture of the venue: http://groups.northwestern.edu/nsc/wp-content/themes/NSC-Custom/images/photos/osu-ballroom.jpg
- [x] Add Google Maps as an iframe: ```<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3056.4802324463963!2d-83.00859630000001!3d39.99771940000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388ebf772f0aad%3A0x3a1cdcf1649d2a83!2sThe+Ohio+Union+at+Ohio+State+University!5e0!3m2!1sen!2s!4v1443944742024" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>```

**Comment by mattfxyz** [comment]
Added the venue information.
