### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by arnabdotorg** [BuckeyeHackers/ohio#54]
instead of copyright, change to "Made with love by Buckeye Hackers, Open Source Club, Electronics Club, ACM-W, Mobile App Developers Club, CWDG, Engineering Career Services, College of Engineering, Department of Computer Science & Engineering and University Libraries."

or something like that

**Comment by KevinPayravi** [comment]
I'm thinking something like this?

![image](https://cloud.githubusercontent.com/assets/7636606/10561148/5a1c9370-74ed-11e5-95bd-062bab0a434f.png)

**Comment by KevinPayravi** [comment]
Pull request made: https://github.com/BuckeyeHackers/ohio/pull/55
