### ISSUE TITLE
Replace video with Daltons new one

### ISSUE THREAD

**Issue by mattfxyz** [BuckeyeHackers/ohio#58]
It's dope.

**Comment by J3RN** [comment]
I can do this. Where can I find said video?

**Comment by mattfxyz** [comment]
I would ask Dalton. Otherwise it should be on the OHIO YouTube. 

-mf

**Comment by KevinPayravi** [comment]
Video: https://www.youtube.com/watch?v=KSEgYQRVuG8

Thanks @J3RN!
