### ISSUE TITLE
Sponsor pics overlap on mobile

### ISSUE THREAD

**Issue by KevinPayravi** [BuckeyeHackers/ohio#67]
On mobile, some of the sponsor pics overlap. This can probably be temporarily fixed by moving some of the images around until they don't overlap.

![image](https://cloud.githubusercontent.com/assets/7636606/10823739/637f0372-7e33-11e5-954f-1e827b7121d1.png)

![image](https://cloud.githubusercontent.com/assets/7636606/10823745/6e8b8a10-7e33-11e5-99f6-fa47b0ca4e6d.png)

**Comment by mattfxyz** [comment]
Thanks, @egladman
