### ISSUE TITLE
Publish a "Steal These Ideas" page

### ISSUE THREAD

**Issue by arnabdotorg** [BuckeyeHackers/ohio#68]
- [ ] Clean up submitted ideas (remove spam)
- [ ] Publish them using Sheetrock to a page
- [ ] Share via Twitter / hackohio2015 slack to participants
- [ ] Link this URL in the participants portal

Ideally, this goes live Nov 14th

**Comment by mattfxyz** [comment]
Should we add this to the live section?

**Comment by KevinPayravi** [comment]
Will work on this tonight (Friday)

**Comment by KevinPayravi** [comment]
Done: http://hack.osu.edu/ideas.html

Need more ideas ASAP.
