### ISSUE TITLE
div.intro is unresponsive due to .master-title width overflow

### ISSUE THREAD

**Issue by egladman** [BuckeyeHackers/ohio#70]

**Comment by egladman** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8713153/10847542/7be5f1cc-7eed-11e5-848d-32c22ffa4e2e.png)


![screenshot-2](https://cloud.githubusercontent.com/assets/8713153/10847558/8c00eb48-7eed-11e5-9d0a-f4f34c213526.png)

**Comment by mattfxyz** [comment]
I just fixed this one
