### ISSUE TITLE
Add a Prizes Section / Page

### ISSUE THREAD

**Issue by arnabdotorg** [BuckeyeHackers/ohio#79]
- [ ] List out prizes with picture, and criterion for prizes (including door prizes)
- [ ] Share with MattF for his keynote

**Comment by KevinPayravi** [comment]
Best I could do on short notice: Add a prize section to the main page, and another to live.html. No pics, which I don't think is bad - don't want to take up too much room, and it wouldn't fit the simplistic theme.

I'm not sure about criteria so I didn't add; I did specify that door prizes can be acquired by attending tech talks.

Lemme know if anything can be improved!
